In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../Data/df.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16312 entries, 0 to 16311
Data columns (total 62 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  16312 non-null  int64
 1   LBXTC       14880 non-null  float64
 2   PHAFSTHR    15986 non-null  float64
 3   RIAGENDR    16312 non-null  float64
 4   RIDRETH3    16312 non-null  float64
 5   RIDAGEYR    16312 non-null  float64
 6   BMXWT       16149 non-null  float64
 7   BMXHT       16150 non-null  float64
 8   BMXBMI      16129 non-null  float64
 9   BPXSY1      14317 non-null  float64
 10  BPXSY2      14722 non-null  float64
 11  BPXSY3      14684 non-null  float64
 12  BPXSY4      839 non-null    float64
 13  BPXDI1      14317 non-null  float64
 14  BPXDI2      14722 non-null  float64
 15  BPXDI3      14684 non-null  float64
 16  BPXDI4      839 non-null    float64
 17  BPXPLS      14925 non-null  float64
 18  BPXPULS     15822 non-null  float64
 19  DR1TKCAL    14643 non-null  float64
 20  DR1TPROT    14643 non-null  float64
 21  DR1TCARB    14643 non-null  float64
 22  DR1TSUGR    14643 non-null  float64
 23  DR1TFIBE    14643 non-null  float64
 24  DR1TTFAT    14643 non-null  float64
 25  DR1TSFAT    14643 non-null  float64
 26  DR1TMFAT    14643 non-null  float64
 27  DR1TPFAT    14643 non-null  float64
 28  DR1TCHOL    14643 non-null  float64
 29  DR1TSODI    14643 non-null  float64
 30  DR1TVD      14643 non-null  float64
 31  DR1TCALC    14643 non-null  float64
 32  DR1TIRON    14643 non-null  float64
 33  DR1TPOTA    14643 non-null  float64
 34  DR1_300     14759 non-null  float64
 35  ALQ110      3362 non-null   float64
 36  ALQ120Q     8703 non-null   float64
 37  ALQ120U     6969 non-null   float64
 38  ALQ130      6975 non-null   float64
 39  BPQ020      12329 non-null  float64
 40  BPQ040A     4130 non-null   float64
 41  BPQ050A     3549 non-null   float64
 42  BPQ080      12329 non-null  float64
 43  BPQ090D     8936 non-null   float64
 44  BPQ100D     2872 non-null   float64
 45  DIQ010      16312 non-null  float64
 46  MCQ160M     11062 non-null  float64
 47  MCQ170M     1178 non-null   float64
 48  SMQ681      12590 non-null  float64
 49  PAQ605      13652 non-null  float64
 50  PAQ610      2458 non-null   float64
 51  PAD615      2439 non-null   float64
 52  PAQ620      13651 non-null  float64
 53  PAQ625      4762 non-null   float64
 54  PAD630      4741 non-null   float64
 55  PAQ650      13648 non-null  float64
 56  PAQ655      4112 non-null   float64
 57  PAD660      4105 non-null   float64
 58  PAQ665      13646 non-null  float64
 59  PAQ670      5844 non-null   float64
 60  PAD675      5832 non-null   float64
 61  KIQ022      5588 non-null   float64
dtypes: float64(61), int64(1)
memory usage: 7.7 MB

In [3]:
df.columns

Index(['Unnamed: 0', 'LBXTC', 'PHAFSTHR', 'RIAGENDR', 'RIDRETH3', 'RIDAGEYR',
       'BMXWT', 'BMXHT', 'BMXBMI', 'BPXSY1', 'BPXSY2', 'BPXSY3', 'BPXSY4',
       'BPXDI1', 'BPXDI2', 'BPXDI3', 'BPXDI4', 'BPXPLS', 'BPXPULS', 'DR1TKCAL',
       'DR1TPROT', 'DR1TCARB', 'DR1TSUGR', 'DR1TFIBE', 'DR1TTFAT', 'DR1TSFAT',
       'DR1TMFAT', 'DR1TPFAT', 'DR1TCHOL', 'DR1TSODI', 'DR1TVD', 'DR1TCALC',
       'DR1TIRON', 'DR1TPOTA', 'DR1_300', 'ALQ110', 'ALQ120Q', 'ALQ120U',
       'ALQ130', 'BPQ020', 'BPQ040A', 'BPQ050A', 'BPQ080', 'BPQ090D',
       'BPQ100D', 'DIQ010', 'MCQ160M', 'MCQ170M', 'SMQ681', 'PAQ605', 'PAQ610',
       'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ650', 'PAQ655', 'PAD660',
       'PAQ665', 'PAQ670', 'PAD675', 'KIQ022'],
      dtype='object')

dropping that unnamed column which is just the index

In [4]:
df.drop('Unnamed: 0',axis=1,inplace=True)

Filtering for only those that have total blood cholesterol counts

In [5]:
df = df[df.LBXTC.notnull()].copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14880 entries, 0 to 16310
Data columns (total 61 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LBXTC     14880 non-null  float64
 1   PHAFSTHR  14880 non-null  float64
 2   RIAGENDR  14880 non-null  float64
 3   RIDRETH3  14880 non-null  float64
 4   RIDAGEYR  14880 non-null  float64
 5   BMXWT     14749 non-null  float64
 6   BMXHT     14750 non-null  float64
 7   BMXBMI    14733 non-null  float64
 8   BPXSY1    13256 non-null  float64
 9   BPXSY2    13630 non-null  float64
 10  BPXSY3    13599 non-null  float64
 11  BPXSY4    780 non-null    float64
 12  BPXDI1    13256 non-null  float64
 13  BPXDI2    13630 non-null  float64
 14  BPXDI3    13599 non-null  float64
 15  BPXDI4    780 non-null    float64
 16  BPXPLS    13815 non-null  float64
 17  BPXPULS   14487 non-null  float64
 18  DR1TKCAL  13579 non-null  float64
 19  DR1TPROT  13579 non-null  float64
 20  DR1TCARB  13579 non-null  float64
 21  DR1TSUGR  13579 non-null  float64
 22  DR1TFIBE  13579 non-null  float64
 23  DR1TTFAT  13579 non-null  float64
 24  DR1TSFAT  13579 non-null  float64
 25  DR1TMFAT  13579 non-null  float64
 26  DR1TPFAT  13579 non-null  float64
 27  DR1TCHOL  13579 non-null  float64
 28  DR1TSODI  13579 non-null  float64
 29  DR1TVD    13579 non-null  float64
 30  DR1TCALC  13579 non-null  float64
 31  DR1TIRON  13579 non-null  float64
 32  DR1TPOTA  13579 non-null  float64
 33  DR1_300   13679 non-null  float64
 34  ALQ110    3180 non-null   float64
 35  ALQ120Q   8321 non-null   float64
 36  ALQ120U   6672 non-null   float64
 37  ALQ130    6677 non-null   float64
 38  BPQ020    11637 non-null  float64
 39  BPQ040A   3929 non-null   float64
 40  BPQ050A   3371 non-null   float64
 41  BPQ080    11637 non-null  float64
 42  BPQ090D   8473 non-null   float64
 43  BPQ100D   2754 non-null   float64
 44  DIQ010    14880 non-null  float64
 45  MCQ160M   10499 non-null  float64
 46  MCQ170M   1134 non-null   float64
 47  SMQ681    11870 non-null  float64
 48  PAQ605    12793 non-null  float64
 49  PAQ610    2345 non-null   float64
 50  PAD615    2326 non-null   float64
 51  PAQ620    12793 non-null  float64
 52  PAQ625    4514 non-null   float64
 53  PAD630    4493 non-null   float64
 54  PAQ650    12790 non-null  float64
 55  PAQ655    3817 non-null   float64
 56  PAD660    3810 non-null   float64
 57  PAQ665    12788 non-null  float64
 58  PAQ670    5493 non-null   float64
 59  PAD675    5481 non-null   float64
 60  KIQ022    5342 non-null   float64
dtypes: float64(61)
memory usage: 7.0 MB

Filtering for only those that fasted 9 hours or more

In [6]:
df = df[df.PHAFSTHR >= 9].copy()
df.drop('PHAFSTHR',axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6555 entries, 1 to 16308
Data columns (total 60 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LBXTC     6555 non-null   float64
 1   RIAGENDR  6555 non-null   float64
 2   RIDRETH3  6555 non-null   float64
 3   RIDAGEYR  6555 non-null   float64
 4   BMXWT     6506 non-null   float64
 5   BMXHT     6504 non-null   float64
 6   BMXBMI    6498 non-null   float64
 7   BPXSY1    6004 non-null   float64
 8   BPXSY2    6185 non-null   float64
 9   BPXSY3    6182 non-null   float64
 10  BPXSY4    347 non-null    float64
 11  BPXDI1    6004 non-null   float64
 12  BPXDI2    6185 non-null   float64
 13  BPXDI3    6182 non-null   float64
 14  BPXDI4    347 non-null    float64
 15  BPXPLS    6263 non-null   float64
 16  BPXPULS   6394 non-null   float64
 17  DR1TKCAL  6090 non-null   float64
 18  DR1TPROT  6090 non-null   float64
 19  DR1TCARB  6090 non-null   float64
 20  DR1TSUGR  6090 non-null   float64
 21  DR1TFIBE  6090 non-null   float64
 22  DR1TTFAT  6090 non-null   float64
 23  DR1TSFAT  6090 non-null   float64
 24  DR1TMFAT  6090 non-null   float64
 25  DR1TPFAT  6090 non-null   float64
 26  DR1TCHOL  6090 non-null   float64
 27  DR1TSODI  6090 non-null   float64
 28  DR1TVD    6090 non-null   float64
 29  DR1TCALC  6090 non-null   float64
 30  DR1TIRON  6090 non-null   float64
 31  DR1TPOTA  6090 non-null   float64
 32  DR1_300   6131 non-null   float64
 33  ALQ110    1534 non-null   float64
 34  ALQ120Q   4022 non-null   float64
 35  ALQ120U   3235 non-null   float64
 36  ALQ130    3238 non-null   float64
 37  BPQ020    5544 non-null   float64
 38  BPQ040A   1903 non-null   float64
 39  BPQ050A   1630 non-null   float64
 40  BPQ080    5544 non-null   float64
 41  BPQ090D   4058 non-null   float64
 42  BPQ100D   1370 non-null   float64
 43  DIQ010    6555 non-null   float64
 44  MCQ160M   5003 non-null   float64
 45  MCQ170M   531 non-null    float64
 46  SMQ681    5672 non-null   float64
 47  PAQ605    6063 non-null   float64
 48  PAQ610    1117 non-null   float64
 49  PAD615    1108 non-null   float64
 50  PAQ620    6063 non-null   float64
 51  PAQ625    2160 non-null   float64
 52  PAD630    2149 non-null   float64
 53  PAQ650    6062 non-null   float64
 54  PAQ655    1739 non-null   float64
 55  PAD660    1736 non-null   float64
 56  PAQ665    6062 non-null   float64
 57  PAQ670    2536 non-null   float64
 58  PAD675    2530 non-null   float64
 59  KIQ022    2571 non-null   float64
dtypes: float64(60)
memory usage: 3.1 MB

Filtering for those that are 20 or older

In [7]:
df = df[df.RIDAGEYR>=20]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5003 entries, 1 to 16308
Data columns (total 60 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LBXTC     5003 non-null   float64
 1   RIAGENDR  5003 non-null   float64
 2   RIDRETH3  5003 non-null   float64
 3   RIDAGEYR  5003 non-null   float64
 4   BMXWT     4970 non-null   float64
 5   BMXHT     4968 non-null   float64
 6   BMXBMI    4962 non-null   float64
 7   BPXSY1    4670 non-null   float64
 8   BPXSY2    4825 non-null   float64
 9   BPXSY3    4826 non-null   float64
 10  BPXSY4    276 non-null    float64
 11  BPXDI1    4670 non-null   float64
 12  BPXDI2    4825 non-null   float64
 13  BPXDI3    4826 non-null   float64
 14  BPXDI4    276 non-null    float64
 15  BPXPLS    4882 non-null   float64
 16  BPXPULS   4883 non-null   float64
 17  DR1TKCAL  4659 non-null   float64
 18  DR1TPROT  4659 non-null   float64
 19  DR1TCARB  4659 non-null   float64
 20  DR1TSUGR  4659 non-null   float64
 21  DR1TFIBE  4659 non-null   float64
 22  DR1TTFAT  4659 non-null   float64
 23  DR1TSFAT  4659 non-null   float64
 24  DR1TMFAT  4659 non-null   float64
 25  DR1TPFAT  4659 non-null   float64
 26  DR1TCHOL  4659 non-null   float64
 27  DR1TSODI  4659 non-null   float64
 28  DR1TVD    4659 non-null   float64
 29  DR1TCALC  4659 non-null   float64
 30  DR1TIRON  4659 non-null   float64
 31  DR1TPOTA  4659 non-null   float64
 32  DR1_300   4692 non-null   float64
 33  ALQ110    1384 non-null   float64
 34  ALQ120Q   3892 non-null   float64
 35  ALQ120U   3113 non-null   float64
 36  ALQ130    3116 non-null   float64
 37  BPQ020    5003 non-null   float64
 38  BPQ040A   1879 non-null   float64
 39  BPQ050A   1620 non-null   float64
 40  BPQ080    5003 non-null   float64
 41  BPQ090D   3879 non-null   float64
 42  BPQ100D   1368 non-null   float64
 43  DIQ010    5003 non-null   float64
 44  MCQ160M   5003 non-null   float64
 45  MCQ170M   531 non-null    float64
 46  SMQ681    4640 non-null   float64
 47  PAQ605    5003 non-null   float64
 48  PAQ610    983 non-null    float64
 49  PAD615    974 non-null    float64
 50  PAQ620    5003 non-null   float64
 51  PAQ625    1795 non-null   float64
 52  PAD630    1785 non-null   float64
 53  PAQ650    5003 non-null   float64
 54  PAQ655    1116 non-null   float64
 55  PAD660    1113 non-null   float64
 56  PAQ665    5003 non-null   float64
 57  PAQ670    2014 non-null   float64
 58  PAD675    2012 non-null   float64
 59  KIQ022    2571 non-null   float64
dtypes: float64(60)
memory usage: 2.3 MB

Replacing systolic and diastolic blood pressures with the median of the four readings.

In [8]:
df['Systolic'] = df[['BPXSY1','BPXSY2','BPXSY3','BPXSY4']].mean(axis=1)
df["Diastolic"] = df[['BPXDI1','BPXDI2','BPXDI3','BPXDI4']].mean(axis=1)
df.drop(['BPXSY1','BPXSY2','BPXSY3','BPXSY4','BPXDI1','BPXDI2','BPXDI3','BPXDI4'],axis=1,inplace=True)

For those that have not been told they have high blood pressure, BPQ020=2, I'm replacing BPQ050A, now taking prescription medication, with 2, no.  
For those that refused or don't know if they have been told they have high blood pressure, I am replacing BPQ020 and BPQ050A with np.nan
For those that have not been told to take prescription medication for high blood pressure, BPQ040A=2, I'm replacing BPQ050A with 2, no, as this question was skipped.
And for those that refused or don't know, I'm replacing the 050A value with np.nan
Then I'm dropping the variable BPQ040A, have you ever been told to take prescription medication

In [9]:
df.loc[df.BPQ020==2,'BPQ050A']=2
df.loc[df.BPQ020==7,'BPQ020']=np.nan
df.loc[df.BPQ020==9,'BPQ020']=np.nan
df.loc[df.BPQ020==7,'BPQ050A']=np.nan
df.loc[df.BPQ020==9,'BPQ050A']=np.nan
df.loc[df.BPQ040A==2,'BPQ050A']=2
df.loc[df.BPQ040A==7,'BPQ050A']=np.nan
df.loc[df.BPQ040A==9,'BPQ050A']=np.nan
df.drop('BPQ040A',axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5003 entries, 1 to 16308
Data columns (total 53 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LBXTC      5003 non-null   float64
 1   RIAGENDR   5003 non-null   float64
 2   RIDRETH3   5003 non-null   float64
 3   RIDAGEYR   5003 non-null   float64
 4   BMXWT      4970 non-null   float64
 5   BMXHT      4968 non-null   float64
 6   BMXBMI     4962 non-null   float64
 7   BPXPLS     4882 non-null   float64
 8   BPXPULS    4883 non-null   float64
 9   DR1TKCAL   4659 non-null   float64
 10  DR1TPROT   4659 non-null   float64
 11  DR1TCARB   4659 non-null   float64
 12  DR1TSUGR   4659 non-null   float64
 13  DR1TFIBE   4659 non-null   float64
 14  DR1TTFAT   4659 non-null   float64
 15  DR1TSFAT   4659 non-null   float64
 16  DR1TMFAT   4659 non-null   float64
 17  DR1TPFAT   4659 non-null   float64
 18  DR1TCHOL   4659 non-null   float64
 19  DR1TSODI   4659 non-null   float64
 20  DR1TVD     4659 non-null   float64
 21  DR1TCALC   4659 non-null   float64
 22  DR1TIRON   4659 non-null   float64
 23  DR1TPOTA   4659 non-null   float64
 24  DR1_300    4692 non-null   float64
 25  ALQ110     1384 non-null   float64
 26  ALQ120Q    3892 non-null   float64
 27  ALQ120U    3113 non-null   float64
 28  ALQ130     3116 non-null   float64
 29  BPQ020     4998 non-null   float64
 30  BPQ050A    4997 non-null   float64
 31  BPQ080     5003 non-null   float64
 32  BPQ090D    3879 non-null   float64
 33  BPQ100D    1368 non-null   float64
 34  DIQ010     5003 non-null   float64
 35  MCQ160M    5003 non-null   float64
 36  MCQ170M    531 non-null    float64
 37  SMQ681     4640 non-null   float64
 38  PAQ605     5003 non-null   float64
 39  PAQ610     983 non-null    float64
 40  PAD615     974 non-null    float64
 41  PAQ620     5003 non-null   float64
 42  PAQ625     1795 non-null   float64
 43  PAD630     1785 non-null   float64
 44  PAQ650     5003 non-null   float64
 45  PAQ655     1116 non-null   float64
 46  PAD660     1113 non-null   float64
 47  PAQ665     5003 non-null   float64
 48  PAQ670     2014 non-null   float64
 49  PAD675     2012 non-null   float64
 50  KIQ022     2571 non-null   float64
 51  Systolic   4878 non-null   float64
 52  Diastolic  4878 non-null   float64
dtypes: float64(53)
memory usage: 2.1 MB

Doing the same for the questionaire regarding high cholesterol

In [10]:
df.loc[df.BPQ080==2,'BPQ100D']=2
df.loc[df.BPQ080==7,'BPQ080']=np.nan
df.loc[df.BPQ080==9,'BPQ080']=np.nan
df.loc[df.BPQ080==7,'BPQ100D']=np.nan
df.loc[df.BPQ080==9,'BPQ100D']=np.nan
df.loc[df.BPQ090D==2,'BPQ100D']=2
df.loc[df.BPQ090D==7,'BPQ100D']=np.nan
df.loc[df.BPQ090D==9,'BPQ100D']=np.nan
df.drop('BPQ090D',axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5003 entries, 1 to 16308
Data columns (total 52 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LBXTC      5003 non-null   float64
 1   RIAGENDR   5003 non-null   float64
 2   RIDRETH3   5003 non-null   float64
 3   RIDAGEYR   5003 non-null   float64
 4   BMXWT      4970 non-null   float64
 5   BMXHT      4968 non-null   float64
 6   BMXBMI     4962 non-null   float64
 7   BPXPLS     4882 non-null   float64
 8   BPXPULS    4883 non-null   float64
 9   DR1TKCAL   4659 non-null   float64
 10  DR1TPROT   4659 non-null   float64
 11  DR1TCARB   4659 non-null   float64
 12  DR1TSUGR   4659 non-null   float64
 13  DR1TFIBE   4659 non-null   float64
 14  DR1TTFAT   4659 non-null   float64
 15  DR1TSFAT   4659 non-null   float64
 16  DR1TMFAT   4659 non-null   float64
 17  DR1TPFAT   4659 non-null   float64
 18  DR1TCHOL   4659 non-null   float64
 19  DR1TSODI   4659 non-null   float64
 20  DR1TVD     4659 non-null   float64
 21  DR1TCALC   4659 non-null   float64
 22  DR1TIRON   4659 non-null   float64
 23  DR1TPOTA   4659 non-null   float64
 24  DR1_300    4692 non-null   float64
 25  ALQ110     1384 non-null   float64
 26  ALQ120Q    3892 non-null   float64
 27  ALQ120U    3113 non-null   float64
 28  ALQ130     3116 non-null   float64
 29  BPQ020     4998 non-null   float64
 30  BPQ050A    4997 non-null   float64
 31  BPQ080     4969 non-null   float64
 32  BPQ100D    4977 non-null   float64
 33  DIQ010     5003 non-null   float64
 34  MCQ160M    5003 non-null   float64
 35  MCQ170M    531 non-null    float64
 36  SMQ681     4640 non-null   float64
 37  PAQ605     5003 non-null   float64
 38  PAQ610     983 non-null    float64
 39  PAD615     974 non-null    float64
 40  PAQ620     5003 non-null   float64
 41  PAQ625     1795 non-null   float64
 42  PAD630     1785 non-null   float64
 43  PAQ650     5003 non-null   float64
 44  PAQ655     1116 non-null   float64
 45  PAD660     1113 non-null   float64
 46  PAQ665     5003 non-null   float64
 47  PAQ670     2014 non-null   float64
 48  PAD675     2012 non-null   float64
 49  KIQ022     2571 non-null   float64
 50  Systolic   4878 non-null   float64
 51  Diastolic  4878 non-null   float64
dtypes: float64(52)
memory usage: 2.0 MB

For those that refused or don't know if they have been diagnosed with diabetes, I'm replacing the values with np.nan

In [11]:
df.loc[df.DIQ010==7,'DIQ010']=np.nan
df.loc[df.DIQ010==9,'DIQ010']=np.nan
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5003 entries, 1 to 16308
Data columns (total 52 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LBXTC      5003 non-null   float64
 1   RIAGENDR   5003 non-null   float64
 2   RIDRETH3   5003 non-null   float64
 3   RIDAGEYR   5003 non-null   float64
 4   BMXWT      4970 non-null   float64
 5   BMXHT      4968 non-null   float64
 6   BMXBMI     4962 non-null   float64
 7   BPXPLS     4882 non-null   float64
 8   BPXPULS    4883 non-null   float64
 9   DR1TKCAL   4659 non-null   float64
 10  DR1TPROT   4659 non-null   float64
 11  DR1TCARB   4659 non-null   float64
 12  DR1TSUGR   4659 non-null   float64
 13  DR1TFIBE   4659 non-null   float64
 14  DR1TTFAT   4659 non-null   float64
 15  DR1TSFAT   4659 non-null   float64
 16  DR1TMFAT   4659 non-null   float64
 17  DR1TPFAT   4659 non-null   float64
 18  DR1TCHOL   4659 non-null   float64
 19  DR1TSODI   4659 non-null   float64
 20  DR1TVD     4659 non-null   float64
 21  DR1TCALC   4659 non-null   float64
 22  DR1TIRON   4659 non-null   float64
 23  DR1TPOTA   4659 non-null   float64
 24  DR1_300    4692 non-null   float64
 25  ALQ110     1384 non-null   float64
 26  ALQ120Q    3892 non-null   float64
 27  ALQ120U    3113 non-null   float64
 28  ALQ130     3116 non-null   float64
 29  BPQ020     4998 non-null   float64
 30  BPQ050A    4997 non-null   float64
 31  BPQ080     4969 non-null   float64
 32  BPQ100D    4977 non-null   float64
 33  DIQ010     5002 non-null   float64
 34  MCQ160M    5003 non-null   float64
 35  MCQ170M    531 non-null    float64
 36  SMQ681     4640 non-null   float64
 37  PAQ605     5003 non-null   float64
 38  PAQ610     983 non-null    float64
 39  PAD615     974 non-null    float64
 40  PAQ620     5003 non-null   float64
 41  PAQ625     1795 non-null   float64
 42  PAD630     1785 non-null   float64
 43  PAQ650     5003 non-null   float64
 44  PAQ655     1116 non-null   float64
 45  PAD660     1113 non-null   float64
 46  PAQ665     5003 non-null   float64
 47  PAQ670     2014 non-null   float64
 48  PAD675     2012 non-null   float64
 49  KIQ022     2571 non-null   float64
 50  Systolic   4878 non-null   float64
 51  Diastolic  4878 non-null   float64
dtypes: float64(52)
memory usage: 2.0 MB

For those that refused or don't know if they have been told they have weak or failing kidneys, I'm replacing the variable's value with np.nan

In [12]:
df.loc[df.KIQ022==7,'KIQ022']=np.nan
df.loc[df.KIQ022==9,'KIQ022']=np.nan

For those that have been told they do not have thyroid problems, I am setting the value for the variable representing do you still have thyroid problems to no, as this was skipped. And for those that refused or don't know, I will replace with nan.
For those that refused or don't know if they still have thyroid problems, I'm replacing the value with nan.
Then I'm dropping the variable about if you have ever been told you have thyroid problems.

In [13]:
df.loc[df.MCQ160M==2,'MCQ170M']=2
df.loc[df.MCQ160M==7,'MCQ170M']=np.nan
df.loc[df.MCQ160M==9,'MCQ170M']=np.nan
df.loc[df.MCQ170M==7,'MCQ170M']=np.nan
df.loc[df.MCQ170M==9,'MCQ170M']=np.nan
df.drop('MCQ160M',axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5003 entries, 1 to 16308
Data columns (total 51 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LBXTC      5003 non-null   float64
 1   RIAGENDR   5003 non-null   float64
 2   RIDRETH3   5003 non-null   float64
 3   RIDAGEYR   5003 non-null   float64
 4   BMXWT      4970 non-null   float64
 5   BMXHT      4968 non-null   float64
 6   BMXBMI     4962 non-null   float64
 7   BPXPLS     4882 non-null   float64
 8   BPXPULS    4883 non-null   float64
 9   DR1TKCAL   4659 non-null   float64
 10  DR1TPROT   4659 non-null   float64
 11  DR1TCARB   4659 non-null   float64
 12  DR1TSUGR   4659 non-null   float64
 13  DR1TFIBE   4659 non-null   float64
 14  DR1TTFAT   4659 non-null   float64
 15  DR1TSFAT   4659 non-null   float64
 16  DR1TMFAT   4659 non-null   float64
 17  DR1TPFAT   4659 non-null   float64
 18  DR1TCHOL   4659 non-null   float64
 19  DR1TSODI   4659 non-null   float64
 20  DR1TVD     4659 non-null   float64
 21  DR1TCALC   4659 non-null   float64
 22  DR1TIRON   4659 non-null   float64
 23  DR1TPOTA   4659 non-null   float64
 24  DR1_300    4692 non-null   float64
 25  ALQ110     1384 non-null   float64
 26  ALQ120Q    3892 non-null   float64
 27  ALQ120U    3113 non-null   float64
 28  ALQ130     3116 non-null   float64
 29  BPQ020     4998 non-null   float64
 30  BPQ050A    4997 non-null   float64
 31  BPQ080     4969 non-null   float64
 32  BPQ100D    4977 non-null   float64
 33  DIQ010     5002 non-null   float64
 34  MCQ170M    4974 non-null   float64
 35  SMQ681     4640 non-null   float64
 36  PAQ605     5003 non-null   float64
 37  PAQ610     983 non-null    float64
 38  PAD615     974 non-null    float64
 39  PAQ620     5003 non-null   float64
 40  PAQ625     1795 non-null   float64
 41  PAD630     1785 non-null   float64
 42  PAQ650     5003 non-null   float64
 43  PAQ655     1116 non-null   float64
 44  PAD660     1113 non-null   float64
 45  PAQ665     5003 non-null   float64
 46  PAQ670     2014 non-null   float64
 47  PAD675     2012 non-null   float64
 48  KIQ022     2568 non-null   float64
 49  Systolic   4878 non-null   float64
 50  Diastolic  4878 non-null   float64
dtypes: float64(51)
memory usage: 2.0 MB

For those that refused or don't know if they smoked tobacco in the past five days, I'm replacing it with nan

In [14]:
df.loc[df.SMQ681==7,'SMQ681']=np.nan
df.loc[df.SMQ681==9,'SMQ681']=np.nan
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5003 entries, 1 to 16308
Data columns (total 51 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LBXTC      5003 non-null   float64
 1   RIAGENDR   5003 non-null   float64
 2   RIDRETH3   5003 non-null   float64
 3   RIDAGEYR   5003 non-null   float64
 4   BMXWT      4970 non-null   float64
 5   BMXHT      4968 non-null   float64
 6   BMXBMI     4962 non-null   float64
 7   BPXPLS     4882 non-null   float64
 8   BPXPULS    4883 non-null   float64
 9   DR1TKCAL   4659 non-null   float64
 10  DR1TPROT   4659 non-null   float64
 11  DR1TCARB   4659 non-null   float64
 12  DR1TSUGR   4659 non-null   float64
 13  DR1TFIBE   4659 non-null   float64
 14  DR1TTFAT   4659 non-null   float64
 15  DR1TSFAT   4659 non-null   float64
 16  DR1TMFAT   4659 non-null   float64
 17  DR1TPFAT   4659 non-null   float64
 18  DR1TCHOL   4659 non-null   float64
 19  DR1TSODI   4659 non-null   float64
 20  DR1TVD     4659 non-null   float64
 21  DR1TCALC   4659 non-null   float64
 22  DR1TIRON   4659 non-null   float64
 23  DR1TPOTA   4659 non-null   float64
 24  DR1_300    4692 non-null   float64
 25  ALQ110     1384 non-null   float64
 26  ALQ120Q    3892 non-null   float64
 27  ALQ120U    3113 non-null   float64
 28  ALQ130     3116 non-null   float64
 29  BPQ020     4998 non-null   float64
 30  BPQ050A    4997 non-null   float64
 31  BPQ080     4969 non-null   float64
 32  BPQ100D    4977 non-null   float64
 33  DIQ010     5002 non-null   float64
 34  MCQ170M    4974 non-null   float64
 35  SMQ681     4639 non-null   float64
 36  PAQ605     5003 non-null   float64
 37  PAQ610     983 non-null    float64
 38  PAD615     974 non-null    float64
 39  PAQ620     5003 non-null   float64
 40  PAQ625     1795 non-null   float64
 41  PAD630     1785 non-null   float64
 42  PAQ650     5003 non-null   float64
 43  PAQ655     1116 non-null   float64
 44  PAD660     1113 non-null   float64
 45  PAQ665     5003 non-null   float64
 46  PAQ670     2014 non-null   float64
 47  PAD675     2012 non-null   float64
 48  KIQ022     2568 non-null   float64
 49  Systolic   4878 non-null   float64
 50  Diastolic  4878 non-null   float64
dtypes: float64(51)
memory usage: 2.0 MB